# (C) Copyright 2021 Hewlett Packard Enterprise Development LP
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airgap-utility
  labels:
    app: airgap-utility
spec:
  selector:
    matchLabels:
      app: airgap-utility
  template:
    metadata:
      labels:
        app: airgap-utility
    spec:
      containers:
      - name: airgap-utility
        image: registry.suse.com/bci/bci-base
        env:
        - name: https_proxy
          value: http://172.28.1.120:3128                     ###  Enter the proxy https URL
        - name: http_prox
          value: http://172.28.1.120:3128                     ###  Enter the proxy https URL
        - name: HTTPS_PROXY
          value: http://172.28.1.120:3128                     ###  Enter the proxy https URL         
        - name: HTTP_PROXY
          value: http://172.28.1.120:3128                     ####  Enter the proxy http URL
        - name: no_proxy                                   
          value: .upc-caas.local                              ####  Enter the no proxy values here
        - name: NO_PROXY                                   
          value: .upc-caas.local                              ####  Enter the no proxy values here
        command: ["/bin/sh"]
        args: ["-c", "sleep infinity"]
        resources: {}
      restartPolicy: Always
      dnsPolicy: ClusterFirst

