apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: airgap-utility
  name: airgap-utility
spec:
  containers:
  - image: registry.suse.com/bci/bci-base
    name: airgap-utility
    env:
    - name: https_proxy
      value: http://172.28.0.121:3128
    - name: http_proxy
      value: http://172.28.0.121:3128
    - name: no_proxy
      value: .upc-caas.local
    command: ["/bin/sleep", "3650d"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}

