apiVersion: apps/v1
kind: Deployment
metadata:
  name: airgap-utility
  labels:
    app: airgap-utility
spec:
  replicas: 2
  selector:
    matchLabels:
      app: airgap-utility
  template:
    metadata:
      labels:
        app: airgap-utility
    spec:
      containers:
      - name: airgap-utility
        image: registry.suse.com/bci/bci-base
        env:
        - name: https_proxy
          value: http://172.28.0.121:3128
        - name: http_proxy
          value: http://172.28.0.121:3128
        - name: no_proxy
          value: .upc-caas.local
        command: ["/bin/sh"]
        args: ["-c", "while true; do zypper install -y skopeo; sleep 20; done"]
        # args: ["-c", "while true; do zypper install -y skopeo; 'zypper addrepo http://download.opensuse.org/repositories/devel:/tools:/scm/15.3/devel:tools:scm.repo'; zypper install python3; zypper install python3-pip; zypper install wget; sleep 200000; done"]

          #command: ["/bin/sh", "-c", "while true; zypper install -y skopeo; sleep 30; 'zypper addrepo http://download.opensuse.org/repositories/devel:/tools:/scm/15.3/devel:tools:scm.repo'; sleep 30; zypper install python3; done"]
        #args: [ "-c", "zypper install -y skopeo"; "sleep 15" ]
        #  - zypper install -y skopeo
        #  - zypper addrepo http://download.opensuse.org/repositories/devel:/tools:/scm/15.3/devel:tools:scm.repo"
        #  - zypper install python3
            #  command: ["/bin/bash", "zypper install python3-pip"]
            #     command: ["/bin/bash", "zypper install wget"]
            #  command: ["/bin/bash", "wget https://ezmeral-platform-releases.s3.amazonaws.com/5.4.1/3073/hpeairgaputil-1.1-py2.py3-none-any.whl"]
            #   command: ["/bin/bash", "pip3 install hpeairgaputil-1.1-py2.py3-none-any.whl"]
        resources: {}
      dnsPolicy: ClusterFirst

