# (C) Copyright 2021 Hewlett Packard Enterprise Development LP
--- 

- name: Set proxy url without credentials
  set_fact:
    proxy_url_https: "https://{{ airgap_proxy_IP }}:{{ airgap_proxy_port }}"
    proxy_url_http: "http://{{ airgap_proxy_IP }}:{{ airgap_proxy_port }}"
  when:
    - airgap_proxy_IP is defined | default('', true) | trim != ''
    - airgap_proxy_port is defined | default('', true) | trim != ''
    - (airgap_proxy_username is not defined) or (airgap_proxy_username |lower == 'none')
    - (airgap_proxy_password is not defined) or (airgap_proxy_password |lower == 'none')

- name: Set customer proxy url with credentials
  set_fact:
    proxy_url_http: "http://{{ airgap_proxy_username }}:{{ airgap_proxy_password }}@{{ airgap_proxy_IP }}:{{ airgap_proxy_port }}"
    proxy_url_https: "https://{{ airgap_proxy_username }}:{{ airgap_proxy_password }}@{{ airgap_proxy_IP }}:{{ airgap_proxy_port }}"
  when:
    - airgap_proxy_IP is defined | default('', true) | trim != ''
    - airgap_proxy_port is defined | default('', true) | trim != ''
    - (airgap_proxy_username is defined) and (airgap_proxy_username |lower != 'none')
    - (airgap_proxy_password is defined) and (airgap_proxy_password |lower != 'none')
 
- name: copying file with playbook
  become: true
  template:
    src: ../templates/airgap-cronjob.yaml.j2
    dest: /tmp/airgap-cronjob.yaml

     
- name: Run command to deploy airgap-utility
  command:
    cmd: kubectl create -f /tmp/airgap-cronjob.yaml -n "{{ airgap_ns }}"
  become: true


