# (C) Copyright 2021 Hewlett Packard Enterprise Development LP
--- 


- name:  Set replication details
  set_fact:
    airgap_replica: 2
  when:
    - airgap_replica is not defined or airgap_replica < 2  
  
- name: copying file with playbook
  become: true
  template:
    src: ../templates/suse/suse-deployment.yaml.j2
    dest: /tmp/suse-deployment-new.yaml

     

- name: Run command to deploy airgap-utility
  command:
    cmd: kubectl create -f /tmp/suse-deployment.yaml -n airgap



