---

- name: Pause for the pod to start
  ansible.builtin.pause:
    seconds: 15

- name: wait for pods to be in Running state
  shell:
    cmd: "kubectl get pods -n airgap -o json"
  register: airgap_get_pods
  until: airgap_get_pods.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]
  retries: 5
  delay: 10

- name: Run command to check internet connectivity
  shell:
    cmd: "kubectl exec -it pod/{{ pod_name.stdout }} -n {{ airgap_ns }} -- curl -I https://linuxconfig.org"
  register: internet_result
  ignore_errors: yes

- name: Fails if Internet not available on Pod
  fail:
    msg: "Internet not available on pod please check proxy"
  when: "'HTTP/1.1 200' not in internet_result.stdout"

- name: Install skopeo and wget
  command:
    cmd: "kubectl exec -it pod/{{ pod_name.stdout }} -n {{ airgap_ns }} -- {{ item }}"
#  register: install_result
  with_items:
    - zypper install -y skopeo wget awk
    - zypper addrepo 'http://download.opensuse.org/repositories/devel:/tools:/scm/15.3/devel:tools:scm.repo'
    - zypper install -y python3 python3-pip
    - wget 'https://ezmeral-platform-releases.s3.amazonaws.com/5.4.3/hpeairgaputil-1.3-py2.py3-none-any.whl'
    - pip3 install hpeairgaputil-1.3-py2.py3-none-any.whl
  ignore_errors: yes

- name: Copy images to Harbor 
  include_tasks: airgap-utility-copy.yaml
