---
#- name: Get list of Components for the Airgap-Utility release
#  shell:
#    cmd: kubectl exec -it pod/"{{ pod_name.stdout }}" -n "{{ airgap_ns }}" -- hpe-airgap-util --list_components --release "{{ airgap_release }}" |awk 'NR>3 {print $2 }'
#  register: components_list

#- shell: 
#    cmd: cat /dev/null > /tmp/airgap1256.txt && cat /dev/null > /tmp/airgap-tmpfile.txt 

#- name: Get list of Images for each Components
#  shell:
#    cmd: "kubectl exec -it pod/{{ pod_name.stdout }} -n {{ airgap_ns }} -- hpe-airgap-util --release {{ airgap_release }} --component {{ item  }} | awk 'NR>4 {print $2}' >>/tmp/airgap1256.txt"
#  with_items:
#    - "{{ components_list.stdout_lines }}"

#- name: Copy image list to file on the K3s master node
#  shell:
#    cmd: grep -v Total /tmp/airgap1256.txt >> /tmp/airgap-tmpfile.txt

#- name: Convert to yaml file
#  shell: 
#    cmd: awk 'NF {print "image"'FNR'":"" "$0}' /tmp/airgap-tmpfile.txt >> /tmp/airgap-tmpfile.yaml
#    cmd: awk 'NF {print " " " " " " "" "-"" "$0}' /tmp/airgap-tmpfile.txt >> /tmp/airgap-tmpfile.yaml


#- name: ansible copy file 
#  fetch:
#    src: /tmp/airgap-tmpfile.yaml
#    dest: /tmp/airgap-tmpfile.yaml
#    flat: yes

#- name: Read the values from the temp file
#  include_vars: 
#    file: /tmp/airgap-tmpfile.yaml
#    name: image_list

#- name: show dictionary
#  ansible.builtin.debug:
#     msg: "{{image_list.image5 }}"
#    msg: " {{item.value}} "
#  loop:
#    - "{{ image_list }}"

- name: Download images to local harbor
  shell:
   cmd: "kubectl exec -it pod/{{ pod_name.stdout }} -n {{ airgap_ns }} -- hpe-airgap-util --release {{ airgap_release }}  --copy --dest_url harbor.{{ domain_name }}/airgap --image {{ item }} --dest_creds 'admin:Password!234'"
  register: download_result
#  loop:
#    - "{{ image_list }}"
#    - "{{ range(0, 300 + 1, 1)|product ( image_list )| list }}"
#    - "{{ list_one |image_list(list_two)|range(0, 300 + 1, 1) }}"
#  loop_control:
#    extended: yes
  with_items:

#   - bluedata/hpecp-bootstrap-airflow:2.1-1
#   - bluedata/hpecp-bootstrap-tools:0.7
#   - postgres:9.5
#   - k8s.gcr.io/volume-nfs:0.8
#   - gcr.io/mapr-252711/airflow-operator:develop-latest
#   - k8s.gcr.io/git-sync/git-sync:v3.3.4
#   - pbweb/airflow-prometheus-exporter:latest
#   - bluedata/hpecp-bootstrap-argocd:2.2.5-2
#   - bluedata/hpecp-bootstrap-tools:0.7
#   - ghcr.io/dexidp/dex:v2.30.2
#   - redis:6.2.6-alpine
#   - gcr.io/mapr-252711/nodeservices-6.2.0:202207071036P152
#   - bluedata/hpecp-bootstrap-tools:0.7
#   - gcr.io/mapr-252711/ldap-6.2.0:202207071036P152
#   - gcr.io/mapr-252711/csi-attacher:v3.3.0
#   - gcr.io/mapr-252711/csi-provisioner:v3.0.0
#   - gcr.io/mapr-252711/csi-nfsplugin:1.0.6
#   - gcr.io/mapr-252711/csi-kdfplugin:1.2.6
#   - gcr.io/mapr-252711/csi-snapshotter:v4.2.1
#   - gcr.io/mapr-252711/livenessprobe:v2.4.0
#   - gcr.io/mapr-252711/snapshot-controller:v4.2.1
#   - gcr.io/mapr-252711/csi-kdfprovisioner:1.2.4
#   - gcr.io/mapr-252711/csi-resizer:v1.3.0
#   - gcr.io/mapr-252711/csi-node-driver-registrar:v2.3.0
#   - gcr.io/mapr-252711/dataplatformvalidator-1.0.0:202207071036P152
#   - gcr.io/mapr-252711/tenantvalidator-1.0.0:202207071036P152
#   - gcr.io/mapr-252711/clusteroperator-1.0.0:202207071036P152
#   - gcr.io/mapr-252711/autoticketgen-1.0.0:202207071036P152
#   - gcr.io/mapr-252711/base-6.2.0:202207071036P152
#   - gcr.io/mapr-252711/hivemeta-2.3.7:202207071036P152
#   - gcr.io/mapr-252711/init-6.2.0:202207071036P152
#   - gcr.io/mapr-252711/tenantoperator-1.0.0:202207071036P152
#   - gcr.io/mapr-252711/cldb-6.2.0:202207071036P152
#   - gcr.io/mapr-252711/kubeflow-operator:v1.1.0-latest
#   - gcr.io/mapr-252711/mfs-6.2.0:202207071036P152
#   - gcr.io/mapr-252711/zookeeper-6.2.0:202207071036P152
#   - gcr.io/mapr-252711/admincli-6.2.0:202207071036P152
#   - gcr.io/mapr-252711/clientbase-6.2.0:202207071036P152
#   - gcr.io/mapr-252711/webserver-6.2.0:202207071036P152
#   - gcr.io/mapr-252711/objectstore-2.2.0:202207071036P152
#   - rancher/local-path-provisioner:v0.0.13
#   - gcr.io/mapr-252711/httpfs-1.1.0:202207071036P152
#   - gcr.io/mapr-252711/maprgateway-6.2.0:202207071036P152
#   - gcr.io/mapr-252711/kafkarest-6.0.0:202207071036P152
#   - gcr.io/mapr-252711/dataaccessgateway-4.0.0:202207071036P152
#   - gcr.io/mapr-252711/elasticsearch-6.8.8:202207071036P152
#   - gcr.io/mapr-252711/collectd-5.12.0:202207071036P152
#   - gcr.io/mapr-252711/fluent-1.10.3:202207071036P152
#   - gcr.io/mapr-252711/grafana-7.5.10:202207071036P152
#   - gcr.io/mapr-252711/kibana-6.8.8:202207071036P152
#   - gcr.io/mapr-252711/tenantcli-6.2.0:202207071036P152
#   - gcr.io/mapr-252711/hsmsetup-6.2.0:202207071036P152
#   - gcr.io/mapr-252711/opentsdb-2.4.1:202207071036P152
#   - gcr.io/mapr-252711/busybox:latest
#   - bluedata/hpecp-bootstrap-falco:0.32.2-0
#   - falcosecurity/falco-no-driver:0.32.2
#   - falcosecurity/falcosidekick:2.26.0
#   - redislabs/redisearch:2.2.4
#   - falcosecurity/falcosidekick-ui:v2.0.2
#   - bluedata/hpecp-bootstrap-hpecp-agent:1.2.5-2
#   - quay.io/kiali/kiali-operator:v1.48.0
#   - bluedata/hpecp-bootstrap-tools:0.7
#   - bluedata/hpecp-fsmount:1.1.1
#   - bluedata/hpecp-agent:1.2.5
#   - bluedata/metricbeat:6.6.6-2.1
#   - bluedata/hpecp-bootstrap-tools:0.7
#   - bluedata/nvidiagpubeat:6.5.5-1.11
#   - bluedata/hpecp-bootstrap-tools:0.7
#   - bluedata/hpecp-bootstrap-tools:0.7
#   - prom/prometheus:v2.37.0
#   - bluedata/hpecp-bootstrap-tools:0.7
#   - grafana/grafana:9.0.5
#   - istio/proxyv2:1.13.5
#   - jaegertracing/all-in-one:1.36
#   - jimmidyson/configmap-reload:v0.7.1
#   - istio/pilot:1.13.5
#   - istio/operator:1.13.5
#   - bluedata/hpecp-bootstrap-tools:0.7
#   - quay.io/coreos/kube-state-metrics:v1.9.6
#   - bluedata/hpecp-bootstrap-kubedirector:0.10.1-10
#   - bluedata/ubuntu18:1.4
#   - bluek8s/kubedirector:0.10.1
#   - bluedata/hpecp-bootstrap-tools:0.7
#   - bluedata/centos7:4.3
#   - curlimages/curl:latest
#   - bluedata/kftokenpod:1.0
#   - bluedata/hpecp-bootstrap-tools:0.7
#   - alpine:3.10
#   - bitnami/kubectl:1.18
#   - bluedata/pytorch:mnist-ddp-cpu
   - docker.io/kfserving/pytorchserver:v0.6.1
   - docker.io/kfserving/pytorchserver:v0.6.1-gpu
   - bluedata/kubeflow-retagged-for-airgap:knative.dev-eventing-cmd-apiserver_receive_adapter-v0.22.1
   - docker.io/kfserving/sklearnserver:v0.6.1
   - busybox:latest
   - busybox:1.28
   - docker.io/kfserving/storage-initializer:v0.6.1
   - docker.io/kfserving/kfserving-controller:v0.6.1
   - docker.io/kubeflowkatib/earlystopping-medianstop:v0.13.0
   - docker.io/kfserving/xgbserver:v0.6.1
   - docker.io/kubeflowkatib/enas-cnn-cifar10-cpu:v0.13.0
   - docker.io/kubeflowkatib/suggestion-chocolate:v0.13.0
   - docker.io/kubeflowkatib/suggestion-enas:v0.13.0
   - docker.io/kubeflowkatib/suggestion-darts:v0.13.0
   - docker.io/kubeflowkatib/pytorch-mnist:v0.13.0
   - docker.io/kubeflowkatib/mxnet-mnist:v0.13.0
   - docker.io/kubeflowkatib/suggestion-hyperband:v0.13.0
   - docker.io/kubeflowkatib/suggestion-hyperopt:v0.13.0
   - docker.io/kubeflowkatib/suggestion-optuna:v0.13.0
   - docker.io/kubeflowkatib/suggestion-skopt:v0.13.0
   - docker.io/seldonio/mlserver:0.2.1
   - docker.io/kubeflowkatib/file-metrics-collector:v0.13.0
   - docker.io/kubeflowkatib/tfevent-metrics-collector:v0.13.0
   - docker.io/kubeflowkatib/suggestion-goptuna:v0.13.0
   - docker.io/seldonio/seldon-core-operator:1.9.0
   - gcr.io/mapr-252711/kubeflow/notebooks/jupyter-tensorflow-1.15.2-gpu:ecp-5.4.0-release
   - gcr.io/mapr-252711/kubeflow/notebooks/jupyter-tensorflow-2.1.0-gpu:ecp-5.4.0-release
   - docker.io/seldonio/seldon-core-executor:1.9.0
   - docker.io/seldonio/engine:1.9.0
   - gcr.io/arrikto/kubeflow/oidc-authservice:2cb5bf6
   - gcr.io/mapr-252711/kubeflow/notebooks/jupyter-tensorflow-1.15.2-cpu:ecp-5.4.0-release
   - gcr.io/mapr-252711/kubeflow/notebooks/jupyter-tensorflow-2.1.0-cpu:ecp-5.4.0-release
   - docker.io/metacontrollerio/metacontroller:v2.0.4
   - gcr.io/google-containers/busybox:latest
   - gcr.io/knative-releases/knative.dev/eventing/cmd/broker/filter:v0.22.1
   - gcr.io/knative-releases/knative.dev/eventing/cmd/broker/ingress:v0.22.1
   - gcr.io/knative-releases/knative.dev/eventing/cmd/controller:v0.22.1
   - gcr.io/mapr-252711/kubeflow/installer:v1.5.0-latest
   - gcr.io/kubeflow-ci/tf-mnist-with-summaries:1.0
   - gcr.io/knative-releases/knative.dev/eventing/cmd/mtping:v0.22.1
   - gcr.io/knative-releases/knative.dev/eventing/cmd/webhook:v0.22.1
   - gcr.io/knative-releases/knative.dev/net-istio/cmd/controller:v0.22.1
   - gcr.io/mapr-252711/kubeflow/minio/console:v1.5.0-latest
   - gcr.io/knative-releases/knative.dev/net-istio/cmd/webhook:v0.22.1
   - gcr.io/knative-releases/knative.dev/serving/cmd/activator:v0.22.1
   - gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler:v0.22.1
   - python:3.7
   - gcr.io/knative-releases/knative.dev/serving/cmd/controller:v0.22.1
   - gcr.io/knative-releases/knative.dev/serving/cmd/queue:v0.22.1
   - gcr.io/knative-releases/knative.dev/serving/cmd/webhook:v0.22.1
   - gcr.io/kubebuilder/kube-rbac-proxy:v0.4.0
   - gcr.io/mapr-252711/kubeflow/argo/init-container:v1.5.0-latest
   - gcr.io/kubeflow-images-public/pytorch-operator:vmaster-g518f9c76
   - gcr.io/mapr-252711/kubeflow/minio/server:v1.5.0-latest
   - gcr.io/mapr-252711/kubeflow/minio/wait-script:v1.5.0-latest
   - gcr.io/mapr-252711/kubeflow/minio/init:v1.5.0-latest
   - gcr.io/mapr-252711/kf-ecp-5.3.0/knative/eventing/channel_broker:v0.22.1
   - gcr.io/mapr-252711/kf-ecp-5.3.0/knative/eventing/channel_dispatcher:v0.22.1
   - gcr.io/mapr-252711/kf-ecp-5.3.0/knative/eventing/channel_controller:v0.22.1
   - gcr.io/mapr-252711/kubeflow/central-dashboard:v1.5.0-latest
   - gcr.io/mapr-252711/kubeflow/kfserving/controller:v0.6.0
   - gcr.io/mapr-252711/kubeflow/ml-pipeline-api-server:kfp-v1.8.0-branch-hpe-latest
   - gcr.io/mapr-252711/kubeflow/notebook-controller:v1.5.0-latest
   - gcr.io/mapr-252711/kubeflow/ml-pipeline-cache-server:kfp-v1.8.0-branch-hpe-latest
   - gcr.io/mapr-252711/kubeflow/seldon/mlflowserver:v1.5.0-latest
   - gcr.io/mapr-252711/kubeflow/profile-controller:v1.5.0-latest
   - gcr.io/mapr-252711/kubeflow/prism/prism-operator:v1.5.0-latest
   - gcr.io/mapr-252711/kubeflow/python-k8s:v1.5.0-latest
   - gcr.io/ml-pipeline/cache-deployer:1.8.1
   - gcr.io/ml-pipeline/argoexec:v3.2.3-license-compliance
   - gcr.io/ml-pipeline/argoexec:v3.1.6-patch-license-compliance
   - gcr.io/mapr-252711/kubeflow/thirdparty/knative/eventing/channel_broker:v0.22.1
   - gcr.io/mapr-252711/kubeflow/thirdparty/knative/eventing/channel_controller:v0.22.1
   - gcr.io/tfx-oss-public/tfx:1.2.0
   - gcr.io/mapr-252711/kubeflow/tensorboard-controller:v1.5.0-latest
   - gcr.io/ml-pipeline/metadata-envoy:1.8.1
   - gcr.io/mapr-252711/kubeflow/thirdparty/knative/eventing/channel_dispatcher:v0.22.1
   - gcr.io/mapr-252711/kubeflow/thirdparty/knative/eventing/pingsource-cleanup:v0.22.1
   - gcr.io/ml-pipeline/frontend:1.8.1
   - gcr.io/ml-pipeline/metadata-writer:1.8.1
   - gcr.io/ml-pipeline/visualization-server:1.8.1
   - gcr.io/ml-pipeline/kfp-launcher:1.7.1
   - gcr.io/ml-pipeline/mysql:5.7
   - gcr.io/ml-pipeline/persistenceagent:1.8.1
   - gcr.io/ml-pipeline/scheduledworkflow:1.8.1
   - gcr.io/ml-pipeline/viewer-crd-controller:1.8.1
   - gcr.io/ml-pipeline/workflow-controller:v3.2.3-license-compliance
   - kadalu/kadalu-operator:0.8.15
   - kadalu/kadalu-csi:0.8.15
   - gcr.io/tfx-oss-public/ml_metadata_store_server:1.0.0
   - gcr.io/tfx-oss-public/ml_metadata_store_server:1.5.0
   - horovod/horovod:0.20.0-tf2.3.0-torch1.6.0-mxnet1.5.0-py3.7-cpu
   - istio/proxyv2:1.13.2
   - istio/proxyv2:1.12.0
   - kfexamples/sandbox:finseries-tensorflow
   - kfexamples/sandbox:seldon-issue-summarization
   - istio/pilot:1.13.2
   - kfexamples/mlflow-cli:1.12.0
   - k8s.gcr.io/pause:3.2
   - kfserving/agent:v0.6.1
   - nvcr.io/nvidia/tritonserver:20.08-py3
   - kfserving/aix-explainer:v0.6.1
   - kfserving/alibi-explainer:v0.6.1
   - kfserving/models-web-app:v0.6.1
   - kfserving/art-explainer:v0.6.1
   - kfserving/lgbserver:v0.6.1
   - kfserving/paddleserver:v0.6.1
   - kubeflow/mxnet-operator:v1.1.0
   - kfserving/pmmlserver:v0.6.1
   - kfserving/kfserving-controller:v0.6.1
   - kubeflow/xgboost-operator:v0.2.0
   - mcr.microsoft.com/onnxruntime/server:v1.0.0
   - kubeflowkatib/katib-db-manager:v0.13.0
   - kubeflowkatib/katib-ui:v0.13.0
   - mysql:8.0.26
   - kubeflowkatib/katib-controller:v0.13.0
   - kubernetesui/metrics-scraper:v1.0.4
   - public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/codeserver-python:v1.3.0-rc.1
   - kubernetesui/dashboard:v2.0.0-rc2
   - metacontroller/metacontroller:v0.3.0
   - mpioperator/kubectl-delivery:latest
   - public.ecr.aws/j1r0q0g6/notebooks/jupyter-web-app:v1.5.0
   - public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/rstudio-tidyverse:v1.3.0-rc.1
   - mpioperator/mpi-operator:v0.2.3
   - nginx:stable-alpine
   - public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter-scipy:v1.3.0-rc.1
   - public.ecr.aws/j1r0q0g6/notebooks/volumes-web-app:v1.5.0
   - public.ecr.aws/j1r0q0g6/notebooks/tensorboards-web-app:v1.5.0
   - seldonio/mlserver:0.3.2
   - seldonio/xgboostserver:1.9.0
   - seldonio/tfserving-proxy:1.9.0
   - seldonio/sklearnserver:1.9.0
   - seldonio/alibiexplainer:1.9.0
   - pytorch/torchserve-kfs:0.4.0
   - pytorch/torchserve-kfs:0.4.0-gpu
   - public.ecr.aws/j1r0q0g6/notebooks/access-management:v1.5.0
   - tensorflow/tensorflow:2.1.0
   - tensorflow/tensorflow:1.11.0-py3
   - seldonio/seldon-core-operator:1.9.0
   - public.ecr.aws/j1r0q0g6/notebooks/admission-webhook:v1.5.0
   - seldonio/seldon-core-executor:1.9.0
   - tensorflow/serving:1.14.0
   - tensorflow/serving:1.14.0-gpu
   - tensorflow/serving:2.1.0
   - quay.io/dexidp/dex:v2.24.0
   - seldonio/rclone-storage-initializer:1.9.0
   - quay.io/jetstack/cert-manager-controller:v1.3.1
   - quay.io/jetstack/cert-manager-cainjector:v1.3.1
   - public.ecr.aws/j1r0q0g6/training/training-operator:174e8813666951ded505daf334a37f60fd50c18d
   - quay.io/jetstack/cert-manager-webhook:v1.3.1
   - k8s.gcr.io/pause:3.2
   - k8s.gcr.io/pause:3.4.1
   - k8s.gcr.io/pause:3.5
   - k8s.gcr.io/coredns:1.7.0
   - k8s.gcr.io/coredns:v1.8.0
   - quay.io/coreos/flannel:v0.15.1
   - k8s.gcr.io/kube-proxy:v1.19.15
   - k8s.gcr.io/kube-proxy:v1.20.11
   - k8s.gcr.io/kube-proxy:v1.21.10
   - docker.io/calico/kube-controllers:v3.23.0
   - k8s.gcr.io/kube-scheduler:v1.19.15
   - k8s.gcr.io/kube-scheduler:v1.20.11
   - k8s.gcr.io/kube-scheduler:v1.21.10
   - docker.io/calico/cni:v3.23.0
   - k8s.gcr.io/kube-apiserver:v1.19.15
   - k8s.gcr.io/kube-apiserver:v1.20.11
   - k8s.gcr.io/kube-apiserver:v1.21.10
   - k8s.gcr.io/kube-controller-manager:v1.19.15
   - k8s.gcr.io/kube-controller-manager:v1.20.11
   - k8s.gcr.io/kube-controller-manager:v1.21.10
   - coredns/coredns:1.8.4
   - docker.io/calico/node:v3.23.0
   - docker.io/nfvpe/multus:v3.7
   - k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.3.0
   - k8s.gcr.io/sig-storage/livenessprobe:v2.4.0
   - k8s.gcr.io/sig-storage/csi-attacher:v3.3.0
   - k8s.gcr.io/sig-storage/csi-snapshotter:v4.2.1
   - k8s.gcr.io/sig-storage/csi-provisioner:v3.0.0
   - k8s.gcr.io/sig-storage/snapshot-controller:v4.2.1
   - docker.io/maprtech/csi-nfsplugin:1.0.6
   - docker.io/maprtech/csi-kdfprovisioner:1.2.4
   - k8s.gcr.io/sig-storage/csi-resizer:v1.3.0
   - docker.io/maprtech/csi-kdfplugin:1.2.6
   - centos:7
   - bluedata/hpecp-bootstrap-tools:0.7
   - kubernetesui/dashboard:v2.6.1
   - kubernetesui/metrics-scraper:v1.0.8
   - bluedata/hpecp-bootstrap-tools:0.7
   - k8s.gcr.io/metrics-server/metrics-server:v0.6.1
   - bluedata/kd-training-api-serving:1.2
   - bluedata/kd-deployment-api-serving:1.0
   - bluedata/mlflow:1.5
   - bluedata/hpecp-bootstrap-nvidia-plugin:1.0.0-beta-6
   - bluedata/hpecp-bootstrap-nvidia-plugin:0.9.0-1
   - bluedata/hpecp-bootstrap-tools:0.7
   - nvcr.io/nvidia/gpu-feature-discovery:v0.6.1
   - nvcr.io/nvidia/k8s-device-plugin:v0.12.2
   - nvcr.io/nvidia/k8s-device-plugin:v0.9.0
   - k8s.gcr.io/nfd/node-feature-discovery:v0.11.1
   - quay.io/kubernetes_incubator/node-feature-discovery:v0.6.0
   - bluedata/hpecp-bootstrap-tools:0.7
   - openpolicyagent/gatekeeper:v3.9.0
   - bluedata/kd-hivemetastore:239-5.4.3-1.2
   - bluedata/kd-livy:070-247-5.4.3-1.2
   - bluedata/kd-livy:070-5.4.3-1.2
   - bluedata/kd-sparkhs:320-5.4.3-1.2
   - bluedata/kd-sparkts:320-5.4.3-1.2
   - gcr.io/mapr-252711/spark-base-3.2.0:202207111050R
   - bluedata/hpecp-bootstrap-spark-operator:1.3.7.1-27f70f8-83f3a7d
   - gcr.io/mapr-252711/spark-3.2.0:202207111050R
   - gcr.io/mapr-252711/spark-py-3.2.0:202207111050R
   - bluedata/hpecp-bootstrap-tools:0.7
   - gcr.io/mapr-252711/spark-base-2.4.7:202207111050R
   - gcr.io/mapr-252711/spark-2.4.7:202207111050R
   - gcr.io/mapr-252711/spark-operator-1.3.7:1.3.7.1-202207250655
   - gcr.io/mapr-252711/spark-py-2.4.7:202207111050R
   - gcr.io/mapr-252711/spark-r-3.2.0:202207111050R
   - gcr.io/mapr-252711/spark-r-2.4.7:202207111050R
   - gcr.io/mapr-252711/spark-hs-3.2.0:202207111050R
   - gcr.io/mapr-252711/spark-hs-2.4.7:202207111050R
   - gcr.io/mapr-252711/spark-ts-2.4.7:202207111050R
   - gcr.io/mapr-252711/spark-ts-3.2.0:202207111050R
   - gcr.io/mapr-252711/spark-client-3.2.0:202207111050R
   - gcr.io/mapr-252711/spark-client-2.4.7:202110120134C
   - gcr.io/mapr-252711/livy-0.7.0:202207111050R
   - gcr.io/mapr-252711/livy-0.7.0-2.4.7:202207111050R
   - gcr.io/mapr-252711/hivemeta-2.3.9:202207111050R
   - gcr.io/mapr-252711/sparkctl-2.4.7:202110072120R





#    - airflow
#    - argocd
#    - datafabric 
#    - falco
#    - hpecp-agent
#    - hpecp-monitoring
#    - hpecp-nvidiagpubeat
#    - hpecp-serviceaccounts
#    - istio
#    - kube-state-metrics
#    - kubedirector 
#    - kubeflow
#    - kubernetes
#    - kubernetes-dashboard
#    - metrics-server
#    - mlops 
#    - nvidia-plugin 
#    - opa-gatekeeper 
#    - spark
#    - spark-operator
#  until:
#    - "'skipped' in download_result.stdout"
#  retries: 5
#  delay: 30
#  tags: image_download
